### PR TITLE
Custom events

### PR DESCRIPTION
**Pull request by romainsalles**
### What does this do and why?
Add [Custom Events](https://docs.airship.com/api/ua/#tag-custom-events).

### Testing
- I tested them against the live API with real auth
- I wrote tests covering these changes
- I've tested for Ruby versions: 2.6.0

### Airship Contribution Agreement

- I've filled out and signed Airship's contribution agreement form.

### CODE REVIEW

**Comment by sarahdactyl71** [comment]
@romainsalles Thank you for contributing to our library. We will review this PR and get back to you as soon as we can.

**Comment by romainsalles** [comment]
Thanks @sarahdactyl71.

Before merging this PR, please look at this one please: https://github.com/urbanairship/ruby-library/pull/123.
When https://github.com/urbanairship/ruby-library/pull/123 is merged, I'll modify this PR to use the new "server" config property.

**Comment by sarahdactyl71** [comment]
@romainsalles merged #123, please reconfigure and adjust the conflicts in common.rb

**Comment by romainsalles** [comment]
Conflits solved @sarahdactyl71 sarahdactyl71 👍

**Review by sarahdactyl71 — APPROVED** [review]
LGTM thanks for the updates

**Pull request merged**
